<template>
  <component :is="iconComponent" :class="iconClasses" :size="size" v-bind="$attrs" />
</template>

<script setup>
import { computed } from 'vue'
import {
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  Loader2,
  X,
  Plus,
  Minus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Search,
  Filter,
  SortAsc,
  SortDesc,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe,
  User,
  Users,
  Settings,
  Download,
  Upload,
  FileText,
  File,
  Image,
  Video,
  Music,
  Star,
  Heart,
  Bookmark,
  Share,
  Copy,
  Link,
  ExternalLink,
  Lock,
  Unlock,
  Shield,
  Key,
  Database,
  Server,
  Cloud,
  Wifi,
  Signal,
  Battery,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Home,
  Building,
  Car,
  Plane,
  Train,
  Bus,
  Ship,
  Bike,
  Walk,
  Compass,
  Navigation,
  Flag,
  Award,
  Gift,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Euro,
  Pound,
  Bitcoin,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  Activity,
  Zap,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  Wind,
  Thermometer,
  Umbrella,
  Camera,
  Video,
  Mic,
  MicOff,
  Headphones,
  Speaker,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Desktop,
  Printer,
  Scanner,
  HardDrive,
  MemoryStick,
  Cpu,
  Mouse,
  Keyboard,
  Gamepad2,
  Controller,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Palette,
  Brush,
  PenTool,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  ListOrdered,
  Quote,
  Code,
  Terminal,
  Command,
  Zap,
  Target,
  Crosshair,
  Aim,
  Scope,
  Telescope,
  Microscope,
  Flask,
  TestTube,
  Atom,
  DNA,
  Leaf,
  Tree,
  Flower,
  Seedling,
  Sprout,
  Plant,
  Cactus,
  Mushroom,
  Apple,
  Banana,
  Orange,
  Lemon,
  Grape,
  Strawberry,
  Cherry,
  Peach,
  Pear,
  Pineapple,
  Watermelon,
  Carrot,
  Broccoli,
  Tomato,
  Potato,
  Onion,
  Garlic,
  Pepper,
  Salt,
  Sugar,
  Coffee,
  Tea,
  Milk,
  Water,
  Wine,
  Beer,
  Cocktail,
  Juice,
  Soda,
  IceCream,
  Cake,
  Cookie,
  Bread,
  Pizza,
  Hamburger,
  HotDog,
  Taco,
  Sushi,
  Fish,
  Chicken,
  Beef,
  Pork,
  Egg,
  Cheese,
  Yogurt,
  Butter,
  Oil,
  Vinegar,
  Ketchup,
  Mustard,
  Mayo,
  Honey,
  Jam,
  Nut,
  Almond,
  Walnut,
  Peanut,
  Cashew,
  Pistachio,
  Coconut,
  Avocado,
  Olive,
  Corn,
  Rice,
  Wheat,
  Barley,
  Oats,
  Quinoa,
  Lentil,
  Bean,
  Pea,
  Chickpea,
  Soybean,
  Tofu,
  Tempeh,
  Seitan,
  Spirulina,
  Chlorella,
  Probiotic,
  Vitamin,
  Mineral,
  Protein,
  Fiber,
  Omega3,
  Antioxidant,
  Probiotic,
  Enzyme,
  Hormone,
  Antibiotic,
  Vaccine,
  Pill,
  Syringe,
  Bandage,
  Thermometer,
  Stethoscope,
  XRay,
  Microscope,
  TestTube,
  Beaker,
  Flask,
  PetriDish,
  Scalpel,
  Forceps,
  Scissors,
  Needle,
  Thread,
  Bandage,
  Gauze,
  Cotton,
  Alcohol,
  Iodine,
  HydrogenPeroxide,
  Antiseptic,
  Disinfectant,
  Soap,
  HandSanitizer,
  Mask,
  Gloves,
  Gown,
  Cap,
  ShoeCovers,
  Goggles,
  FaceShield,
  Respirator,
  Ventilator,
  Defibrillator,
  Pacemaker,
  HearingAid,
  Glasses,
  ContactLens,
  Crutches,
  Wheelchair,
  Walker,
  Cane,
  Brace,
  Cast,
  Splint,
  Sling,
  NeckBrace,
  BackBrace,
  KneeBrace,
  AnkleBrace,
  WristBrace,
  ElbowBrace,
  ShoulderBrace,
  HipBrace,
  CompressionSock,
  CompressionSleeve,
  HeatingPad,
  IcePack,
  HotWaterBottle,
  ElectricBlanket,
  Massager,
  TENS,
  Ultrasound,
  Laser,
  Radiation,
  Chemotherapy,
  Dialysis,
  Transplant,
  Surgery,
  Anesthesia,
  Sedation,
  PainKiller,
  AntiInflammatory,
  Antibiotic,
  Antiviral,
  Antifungal,
  Antiparasitic,
  Antihistamine,
  Decongestant,
  Expectorant,
  CoughSuppressant,
  Bronchodilator,
  Inhaler,
  Nebulizer,
  Oxygen,
  Ventilator,
  CPAP,
  BiPAP,
  PulseOximeter,
  BloodPressure,
  HeartRate,
  Temperature,
  Weight,
  Height,
  BMI,
  BodyFat,
  MuscleMass,
  BoneDensity,
  BloodSugar,
  Cholesterol,
  Triglycerides,
  UricAcid,
  Creatinine,
  BUN,
  Albumin,
  Hemoglobin,
  WhiteBloodCells,
  Platelets,
  RedBloodCells,
  Lymphocytes,
  Neutrophils,
  Eosinophils,
  Basophils,
  Monocytes,
  ESR,
  CRP,
  Troponin,
  BNP,
  Ddimer,
  PT,
  PTT,
  INR,
  Fibrinogen,
  Antithrombin,
  ProteinC,
  ProteinS,
  FactorV,
  FactorVIII,
  VonWillebrand,
  Fibrinogen,
  Plasminogen,
  TPA,
  Urokinase,
  Streptokinase,
  Heparin,
  Warfarin,
  Aspirin,
  Clopidogrel,
  Ticagrelor,
  Prasugrel,
  Dabigatran,
  Rivaroxaban,
  Apixaban,
  Edoxaban,
  Betrixaban,
  Fondaparinux,
  Enoxaparin,
  Dalteparin,
  Tinzaparin,
  Nadroparin,
  Bemiparin,
  Certoparin,
  Reviparin,
  Parnaparin,
  Danaparoid,
  Lepirudin,
  Bivalirudin,
  Argatroban,
  Desirudin,
  Melagatran,
  Ximelagatran,
  Dabigatran,
  Rivaroxaban,
  Apixaban,
  Edoxaban,
  Betrixaban,
  Fondaparinux,
  Enoxaparin,
  Dalteparin,
  Tinzaparin,
  Nadroparin,
  Bemiparin,
  Certoparin,
  Reviparin,
  Parnaparin,
  Danaparoid,
  Lepirudin,
  Bivalirudin,
  Argatroban,
  Desirudin,
  Melagatran,
  Ximelagatran,
} from 'lucide-vue-next'

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  size: {
    type: [String, Number],
    default: 24,
  },
  class: {
    type: String,
    default: '',
  },
})

// Маппинг имен иконок на компоненты
const iconMap = {
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  info: Info,
  'loader-2': Loader2,
  x: X,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  'trash-2': Trash2,
  eye: Eye,
  'eye-off': EyeOff,
  search: Search,
  filter: Filter,
  'sort-asc': SortAsc,
  'sort-desc': SortDesc,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  calendar: Calendar,
  clock: Clock,
  'map-pin': MapPin,
  phone: Phone,
  mail: Mail,
  globe: Globe,
  user: User,
  users: Users,
  settings: Settings,
  download: Download,
  upload: Upload,
  'file-text': FileText,
  file: File,
  image: Image,
  video: Video,
  music: Music,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  share: Share,
  copy: Copy,
  link: Link,
  'external-link': ExternalLink,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  key: Key,
  database: Database,
  server: Server,
  cloud: Cloud,
  wifi: Wifi,
  signal: Signal,
  battery: Battery,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  play: Play,
  pause: Pause,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  rewind: Rewind,
  'fast-forward': FastForward,
  home: Home,
  building: Building,
  car: Car,
  plane: Plane,
  train: Train,
  bus: Bus,
  ship: Ship,
  bike: Bike,
  walk: Walk,
  compass: Compass,
  navigation: Navigation,
  flag: Flag,
  award: Award,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  euro: Euro,
  pound: Pound,
  bitcoin: Bitcoin,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart-3': BarChart3,
  'pie-chart': PieChart,
  activity: Activity,
  zap: Zap,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  wind: Wind,
  thermometer: Thermometer,
  umbrella: Umbrella,
  camera: Camera,
  video: Video,
  mic: Mic,
  'mic-off': MicOff,
  headphones: Headphones,
  speaker: Speaker,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  desktop: Desktop,
  printer: Printer,
  scanner: Scanner,
  'hard-drive': HardDrive,
  'memory-stick': MemoryStick,
  cpu: Cpu,
  mouse: Mouse,
  keyboard: Keyboard,
  'gamepad-2': Gamepad2,
  controller: Controller,
  'dice-1': Dice1,
  'dice-2': Dice2,
  'dice-3': Dice3,
  'dice-4': Dice4,
  'dice-5': Dice5,
  'dice-6': Dice6,
  palette: Palette,
  brush: Brush,
  'pen-tool': PenTool,
  type: Type,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  'align-justify': AlignJustify,
  list: List,
  'list-ordered': ListOrdered,
  quote: Quote,
  code: Code,
  terminal: Terminal,
  command: Command,
  target: Target,
  crosshair: Crosshair,
  aim: Aim,
  scope: Scope,
  telescope: Telescope,
  microscope: Microscope,
  flask: Flask,
  'test-tube': TestTube,
  atom: Atom,
  dna: DNA,
  leaf: Leaf,
  tree: Tree,
  flower: Flower,
  seedling: Seedling,
  sprout: Sprout,
  plant: Plant,
  cactus: Cactus,
  mushroom: Mushroom,
  apple: Apple,
  banana: Banana,
  orange: Orange,
  lemon: Lemon,
  grape: Grape,
  strawberry: Strawberry,
  cherry: Cherry,
  peach: Peach,
  pear: Pear,
  pineapple: Pineapple,
  watermelon: Watermelon,
  carrot: Carrot,
  broccoli: Broccoli,
  tomato: Tomato,
  potato: Potato,
  onion: Onion,
  garlic: Garlic,
  pepper: Pepper,
  salt: Salt,
  sugar: Sugar,
  coffee: Coffee,
  tea: Tea,
  milk: Milk,
  water: Water,
  wine: Wine,
  beer: Beer,
  cocktail: Cocktail,
  juice: Juice,
  soda: Soda,
  'ice-cream': IceCream,
  cake: Cake,
  cookie: Cookie,
  bread: Bread,
  pizza: Pizza,
  hamburger: Hamburger,
  'hot-dog': HotDog,
  taco: Taco,
  sushi: Sushi,
  fish: Fish,
  chicken: Chicken,
  beef: Beef,
  pork: Pork,
  egg: Egg,
  cheese: Cheese,
  yogurt: Yogurt,
  butter: Butter,
  oil: Oil,
  vinegar: Vinegar,
  ketchup: Ketchup,
  mustard: Mustard,
  mayo: Mayo,
  honey: Honey,
  jam: Jam,
  nut: Nut,
  almond: Almond,
  walnut: Walnut,
  peanut: Peanut,
  cashew: Cashew,
  pistachio: Pistachio,
  coconut: Coconut,
  avocado: Avocado,
  olive: Olive,
  corn: Corn,
  rice: Rice,
  wheat: Wheat,
  barley: Barley,
  oats: Oats,
  quinoa: Quinoa,
  lentil: Lentil,
  bean: Bean,
  pea: Pea,
  chickpea: Chickpea,
  soybean: Soybean,
  tofu: Tofu,
  tempeh: Tempeh,
  seitan: Seitan,
  spirulina: Spirulina,
  chlorella: Chlorella,
  probiotic: Probiotic,
  vitamin: Vitamin,
  mineral: Mineral,
  protein: Protein,
  fiber: Fiber,
  'omega-3': Omega3,
  antioxidant: Antioxidant,
  enzyme: Enzyme,
  hormone: Hormone,
  antibiotic: Antibiotic,
  vaccine: Vaccine,
  pill: Pill,
  syringe: Syringe,
  bandage: Bandage,
  stethoscope: Stethoscope,
  'x-ray': XRay,
  'petri-dish': PetriDish,
  scalpel: Scalpel,
  forceps: Forceps,
  scissors: Scissors,
  needle: Needle,
  thread: Thread,
  gauze: Gauze,
  cotton: Cotton,
  alcohol: Alcohol,
  iodine: Iodine,
  'hydrogen-peroxide': HydrogenPeroxide,
  antiseptic: Antiseptic,
  disinfectant: Disinfectant,
  soap: Soap,
  'hand-sanitizer': HandSanitizer,
  mask: Mask,
  gloves: Gloves,
  gown: Gown,
  cap: Cap,
  'shoe-covers': ShoeCovers,
  goggles: Goggles,
  'face-shield': FaceShield,
  respirator: Respirator,
  ventilator: Ventilator,
  defibrillator: Defibrillator,
  pacemaker: Pacemaker,
  'hearing-aid': HearingAid,
  glasses: Glasses,
  'contact-lens': ContactLens,
  crutches: Crutches,
  wheelchair: Wheelchair,
  walker: Walker,
  cane: Cane,
  brace: Brace,
  cast: Cast,
  splint: Splint,
  sling: Sling,
  'neck-brace': NeckBrace,
  'back-brace': BackBrace,
  'knee-brace': KneeBrace,
  'ankle-brace': AnkleBrace,
  'wrist-brace': WristBrace,
  'elbow-brace': ElbowBrace,
  'shoulder-brace': ShoulderBrace,
  'hip-brace': HipBrace,
  'compression-sock': CompressionSock,
  'compression-sleeve': CompressionSleeve,
  'heating-pad': HeatingPad,
  'ice-pack': IcePack,
  'hot-water-bottle': HotWaterBottle,
  'electric-blanket': ElectricBlanket,
  massager: Massager,
  tens: TENS,
  ultrasound: Ultrasound,
  laser: Laser,
  radiation: Radiation,
  chemotherapy: Chemotherapy,
  dialysis: Dialysis,
  transplant: Transplant,
  surgery: Surgery,
  anesthesia: Anesthesia,
  sedation: Sedation,
  'pain-killer': PainKiller,
  'anti-inflammatory': AntiInflammatory,
  antiviral: Antiviral,
  antifungal: Antifungal,
  antiparasitic: Antiparasitic,
  antihistamine: Antihistamine,
  decongestant: Decongestant,
  expectorant: Expectorant,
  'cough-suppressant': CoughSuppressant,
  bronchodilator: Bronchodilator,
  inhaler: Inhaler,
  nebulizer: Nebulizer,
  oxygen: Oxygen,
  cpap: CPAP,
  bipap: BiPAP,
  'pulse-oximeter': PulseOximeter,
  'blood-pressure': BloodPressure,
  'heart-rate': HeartRate,
  temperature: Temperature,
  weight: Weight,
  height: Height,
  bmi: BMI,
  'body-fat': BodyFat,
  'muscle-mass': MuscleMass,
  'bone-density': BoneDensity,
  'blood-sugar': BloodSugar,
  cholesterol: Cholesterol,
  triglycerides: Triglycerides,
  'uric-acid': UricAcid,
  creatinine: Creatinine,
  bun: BUN,
  albumin: Albumin,
  hemoglobin: Hemoglobin,
  'white-blood-cells': WhiteBloodCells,
  platelets: Platelets,
  'red-blood-cells': RedBloodCells,
  lymphocytes: Lymphocytes,
  neutrophils: Neutrophils,
  eosinophils: Eosinophils,
  basophils: Basophils,
  monocytes: Monocytes,
  esr: ESR,
  crp: CRP,
  troponin: Troponin,
  bnp: BNP,
  'd-dimer': Ddimer,
  pt: PT,
  ptt: PTT,
  inr: INR,
  fibrinogen: Fibrinogen,
  antithrombin: Antithrombin,
  'protein-c': ProteinC,
  'protein-s': ProteinS,
  'factor-v': FactorV,
  'factor-viii': FactorVIII,
  'von-willebrand': VonWillebrand,
  plasminogen: Plasminogen,
  tpa: TPA,
  urokinase: Urokinase,
  streptokinase: Streptokinase,
  heparin: Heparin,
  warfarin: Warfarin,
  aspirin: Aspirin,
  clopidogrel: Clopidogrel,
  ticagrelor: Ticagrelor,
  prasugrel: Prasugrel,
  dabigatran: Dabigatran,
  rivaroxaban: Rivaroxaban,
  apixaban: Apixaban,
  edoxaban: Edoxaban,
  betrixaban: Betrixaban,
  fondaparinux: Fondaparinux,
  enoxaparin: Enoxaparin,
  dalteparin: Dalteparin,
  tinzaparin: Tinzaparin,
  nadroparin: Nadroparin,
  bemiparin: Bemiparin,
  certoparin: Certoparin,
  reviparin: Reviparin,
  parnaparin: Parnaparin,
  danaparoid: Danaparoid,
  lepirudin: Lepirudin,
  bivalirudin: Bivalirudin,
  argatroban: Argatroban,
  desirudin: Desirudin,
  melagatran: Melagatran,
  ximelagatran: Ximelagatran,
}

// Вычисляем компонент иконки
const iconComponent = computed(() => {
  const component = iconMap[props.name]
  if (!component) {
    console.warn(`Icon "${props.name}" not found`)
    return Info // Fallback иконка
  }
  return component
})

// Вычисляем классы
const iconClasses = computed(() => {
  return `icon icon--${props.name} ${props.class}`.trim()
})
</script>

<style scoped>
.icon {
  display: inline-block;
  vertical-align: middle;
  flex-shrink: 0;
}

/* Анимация для loader-2 */
.icon--loader-2 {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
</style>
