<template>
  <component :is="iconComponent" :class="iconClasses" :size="size" v-bind="$attrs" />
</template>

<script setup>
import { computed } from 'vue'
import {
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  Loader2,
  X,
  Plus,
  Minus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Search,
  Filter,
  SortAsc,
  SortDesc,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe,
  User,
  Users,
  Settings,
  Download,
  Upload,
  FileText,
  File,
  Image,
  Video,
  Music,
  Star,
  Heart,
  Bookmark,
  Share,
  Copy,
  Link,
  ExternalLink,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  AlertCircle,
  HelpCircle,
  Check,
  Home,
  Menu,
  Grid,
  List,
  MoreHorizontal,
  MoreVertical,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  RefreshCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Monitor,
  Smartphone,
  Tablet,
  Printer,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Mic,
  MicOff,
  Camera,
  VideoOff,
  Headphones,
  Speaker,
  Bluetooth,
  BluetoothOff,
  Airplay,
  Cast,
  Chrome,
  Firefox,
  Safari,
  Edge,
  Database,
  Server,
  HardDrive,
  Cpu,
  MemoryStick,
  Mouse,
  Keyboard,
  Gamepad2,
  Controller,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Crown,
  Trophy,
  Medal,
  Award,
  Gift,
  Package,
  ShoppingBag,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Euro,
  Pound,
  Bitcoin,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Target,
  Flag,
  Map,
  Compass,
  Navigation,
  Navigation2,
  Route,
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Bike,
  Walk,
  Run,
  Hiking,
  Mountain,
  Tree,
  Leaf,
  Flower,
  Seedling,
  Sprout,
  Plant,
  Cactus,
  Mushroom,
  Apple,
  Banana,
  Orange,
  Lemon,
  Grape,
  Strawberry,
  Cherry,
  Peach,
  Pear,
  Pineapple,
  Watermelon,
  Carrot,
  Broccoli,
  Corn,
  Tomato,
  Potato,
  Onion,
  Garlic,
  Pepper,
  Salt,
  Sugar,
  Coffee,
  Tea,
  Wine,
  Beer,
  Cocktail,
  Juice,
  Water,
  Soda,
  IceCream,
  Cake,
  Cookie,
  Bread,
  Pizza,
  Hamburger,
  HotDog,
  Taco,
  Sushi,
  Rice,
  Noodles,
  Soup,
  Salad,
  Sandwich,
  Steak,
  Chicken,
  Fish,
  Shrimp,
  Lobster,
  Crab,
  Oyster,
  Mussel,
  Clam,
  Scallop,
  Octopus,
  Squid,
  Jellyfish,
  Starfish,
  Seaweed,
  Coral,
  Shell,
  Pearl,
  Diamond,
  Ruby,
  Emerald,
  Sapphire,
  Amethyst,
  Topaz,
  Opal,
  Jade,
  Turquoise,
  LapisLazuli,
  Malachite,
  Obsidian,
  Granite,
  Marble,
  Limestone,
  Sandstone,
  Shale,
  Clay,
  Mud,
  Sand,
  Gravel,
  Pebble,
  Boulder,
  Rock,
  Stone,
  Crystal,
  Gem,
  Jewel,
  Treasure,
  Gold,
  Silver,
  Bronze,
  Copper,
  Iron,
  Steel,
  Aluminum,
  Titanium,
  Platinum,
  Palladium,
  Rhodium,
  Iridium,
  Osmium,
  Ruthenium,
  Rhenium,
  Tungsten,
  Molybdenum,
  Vanadium,
  Chromium,
  Manganese,
  Cobalt,
  Nickel,
  Zinc,
  Cadmium,
  Mercury,
  Lead,
  Tin,
  Antimony,
  Bismuth,
  Polonium,
  Astatine,
  Radon,
  Francium,
  Radium,
  Actinium,
  Thorium,
  Protactinium,
  Uranium,
  Neptunium,
  Plutonium,
  Americium,
  Curium,
  Berkelium,
  Californium,
  Einsteinium,
  Fermium,
  Mendelevium,
  Nobelium,
  Lawrencium,
  Rutherfordium,
  Dubnium,
  Seaborgium,
  Bohrium,
  Hassium,
  Meitnerium,
  Darmstadtium,
  Roentgenium,
  Copernicium,
  Nihonium,
  Flerovium,
  Moscovium,
  Livermorium,
  Tennessine,
  Oganesson,
} from 'lucide-vue-next'

const props = defineProps({
  name: {
    type: String,
    required: true,
  },
  size: {
    type: [String, Number],
    default: 24,
  },
  class: {
    type: String,
    default: '',
  },
})

// Карта иконок
const iconMap = {
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  info: Info,
  'loader-2': Loader2,
  x: X,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  'trash-2': Trash2,
  eye: Eye,
  'eye-off': EyeOff,
  search: Search,
  filter: Filter,
  'sort-asc': SortAsc,
  'sort-desc': SortDesc,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  calendar: Calendar,
  clock: Clock,
  'map-pin': MapPin,
  phone: Phone,
  mail: Mail,
  globe: Globe,
  user: User,
  users: Users,
  settings: Settings,
  download: Download,
  upload: Upload,
  'file-text': FileText,
  file: File,
  image: Image,
  video: Video,
  music: Music,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  share: Share,
  copy: Copy,
  link: Link,
  'external-link': ExternalLink,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  shield: Shield,
  'shield-check': ShieldCheck,
  'alert-circle': AlertCircle,
  'help-circle': HelpCircle,
  check: Check,
  home: Home,
  menu: Menu,
  grid: Grid,
  list: List,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  maximize: Maximize,
  minimize: Minimize,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  printer: Printer,
  wifi: Wifi,
  'wifi-off': WifiOff,
  battery: Battery,
  'battery-charging': BatteryCharging,
  volume: Volume,
  'volume-x': VolumeX,
  'volume-1': Volume1,
  'volume-2': Volume2,
  mic: Mic,
  'mic-off': MicOff,
  camera: Camera,
  'video-off': VideoOff,
  headphones: Headphones,
  speaker: Speaker,
  bluetooth: Bluetooth,
  'bluetooth-off': BluetoothOff,
  airplay: Airplay,
  cast: Cast,
  chrome: Chrome,
  firefox: Firefox,
  safari: Safari,
  edge: Edge,
  database: Database,
  server: Server,
  'hard-drive': HardDrive,
  cpu: Cpu,
  'memory-stick': MemoryStick,
  mouse: Mouse,
  keyboard: Keyboard,
  'gamepad-2': Gamepad2,
  controller: Controller,
  'dice-1': Dice1,
  'dice-2': Dice2,
  'dice-3': Dice3,
  'dice-4': Dice4,
  'dice-5': Dice5,
  'dice-6': Dice6,
  crown: Crown,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  gift: Gift,
  package: Package,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  euro: Euro,
  pound: Pound,
  bitcoin: Bitcoin,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart-3': BarChart3,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  activity: Activity,
  target: Target,
  flag: Flag,
  map: Map,
  compass: Compass,
  navigation: Navigation,
  'navigation-2': Navigation2,
  route: Route,
  car: Car,
  bus: Bus,
  train: Train,
  plane: Plane,
  ship: Ship,
  bike: Bike,
  walk: Walk,
  run: Run,
  hiking: Hiking,
  mountain: Mountain,
  tree: Tree,
  leaf: Leaf,
  flower: Flower,
  seedling: Seedling,
  sprout: Sprout,
  plant: Plant,
  cactus: Cactus,
  mushroom: Mushroom,
  apple: Apple,
  banana: Banana,
  orange: Orange,
  lemon: Lemon,
  grape: Grape,
  strawberry: Strawberry,
  cherry: Cherry,
  peach: Peach,
  pear: Pear,
  pineapple: Pineapple,
  watermelon: Watermelon,
  carrot: Carrot,
  broccoli: Broccoli,
  corn: Corn,
  tomato: Tomato,
  potato: Potato,
  onion: Onion,
  garlic: Garlic,
  pepper: Pepper,
  salt: Salt,
  sugar: Sugar,
  coffee: Coffee,
  tea: Tea,
  wine: Wine,
  beer: Beer,
  cocktail: Cocktail,
  juice: Juice,
  water: Water,
  soda: Soda,
  'ice-cream': IceCream,
  cake: Cake,
  cookie: Cookie,
  bread: Bread,
  pizza: Pizza,
  hamburger: Hamburger,
  'hot-dog': HotDog,
  taco: Taco,
  sushi: Sushi,
  rice: Rice,
  noodles: Noodles,
  soup: Soup,
  salad: Salad,
  sandwich: Sandwich,
  steak: Steak,
  chicken: Chicken,
  fish: Fish,
  shrimp: Shrimp,
  lobster: Lobster,
  crab: Crab,
  oyster: Oyster,
  mussel: Mussel,
  clam: Clam,
  scallop: Scallop,
  octopus: Octopus,
  squid: Squid,
  jellyfish: Jellyfish,
  starfish: Starfish,
  seaweed: Seaweed,
  coral: Coral,
  shell: Shell,
  pearl: Pearl,
  diamond: Diamond,
  ruby: Ruby,
  emerald: Emerald,
  sapphire: Sapphire,
  amethyst: Amethyst,
  topaz: Topaz,
  opal: Opal,
  jade: Jade,
  turquoise: Turquoise,
  'lapis-lazuli': LapisLazuli,
  malachite: Malachite,
  obsidian: Obsidian,
  granite: Granite,
  marble: Marble,
  limestone: Limestone,
  sandstone: Sandstone,
  shale: Shale,
  clay: Clay,
  mud: Mud,
  sand: Sand,
  gravel: Gravel,
  pebble: Pebble,
  boulder: Boulder,
  rock: Rock,
  stone: Stone,
  crystal: Crystal,
  gem: Gem,
  jewel: Jewel,
  treasure: Treasure,
  gold: Gold,
  silver: Silver,
  bronze: Bronze,
  copper: Copper,
  iron: Iron,
  steel: Steel,
  aluminum: Aluminum,
  titanium: Titanium,
  platinum: Platinum,
  palladium: Palladium,
  rhodium: Rhodium,
  iridium: Iridium,
  osmium: Osmium,
  ruthenium: Ruthenium,
  rhenium: Rhenium,
  tungsten: Tungsten,
  molybdenum: Molybdenum,
  vanadium: Vanadium,
  chromium: Chromium,
  manganese: Manganese,
  cobalt: Cobalt,
  nickel: Nickel,
  zinc: Zinc,
  cadmium: Cadmium,
  mercury: Mercury,
  lead: Lead,
  tin: Tin,
  antimony: Antimony,
  bismuth: Bismuth,
  polonium: Polonium,
  astatine: Astatine,
  radon: Radon,
  francium: Francium,
  radium: Radium,
  actinium: Actinium,
  thorium: Thorium,
  protactinium: Protactinium,
  uranium: Uranium,
  neptunium: Neptunium,
  plutonium: Plutonium,
  americium: Americium,
  curium: Curium,
  berkelium: Berkelium,
  californium: Californium,
  einsteinium: Einsteinium,
  fermium: Fermium,
  mendelevium: Mendelevium,
  nobelium: Nobelium,
  lawrencium: Lawrencium,
  rutherfordium: Rutherfordium,
  dubnium: Dubnium,
  seaborgium: Seaborgium,
  bohrium: Bohrium,
  hassium: Hassium,
  meitnerium: Meitnerium,
  darmstadtium: Darmstadtium,
  roentgenium: Roentgenium,
  copernicium: Copernicium,
  nihonium: Nihonium,
  flerovium: Flerovium,
  moscovium: Moscovium,
  livermorium: Livermorium,
  tennessine: Tennessine,
  oganesson: Oganesson,
}

// Вычисляемое свойство для получения компонента иконки
const iconComponent = computed(() => {
  const icon = iconMap[props.name]
  if (!icon) {
    console.warn(`Icon "${props.name}" not found, using Info as fallback`)
    return Info
  }
  return icon
})

// Вычисляемое свойство для классов иконки
const iconClasses = computed(() => {
  const classes = ['icon']

  // Добавляем анимацию для loader-2
  if (props.name === 'loader-2') {
    classes.push('animate-spin')
  }

  // Добавляем пользовательские классы
  if (props.class) {
    classes.push(props.class)
  }

  return classes.join(' ')
})
</script>

<style scoped>
.icon {
  display: inline-block;
  vertical-align: middle;
}

.animate-spin {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
</style>
